---
# tasks file for networkAnalysis

- name: get vCenter network config for {{ vm_name }}
  community.vmware.vmware_guest_network:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_dc }}'
    validate_certs: false
    name: '{{ vm_name }}'
    gather_network_info: true
  register: network_info
  tags: network

- name: Dump network_info to a trace file
  copy:
    content: "{{ network_info | to_nice_json }}"
    dest: "{{ debug_path }}/network_info_{{ ansible_date_time.iso8601 | regex_replace(':','-') }}.json"
  tags: [ never, debug ]

- name: extract nic info based on network_map
  set_fact:
    guestNic: "{{ guestNic | default([]) + [ {'vlan': mapped_vlan, 'mac': item.mac_addr}] }}"
  loop: "{{ network_info.network_info }}"
  vars:
    mapped_vlan: "{{ network_map.get(item.network_name, 'UNMAPPED') }}"
  when: mapped_vlan != 'UNMAPPED'
  no_log: false
  tags: network

- name: Dump guestNic to a trace file
  copy:
    content: "{{ guestNic | to_nice_json }}"
    dest: "{{ debug_path }}/guestNic_{{ ansible_date_time.iso8601 | regex_replace(':','-') }}.json"
  tags: [ never, debug ]


